name: CI

on:
  push:
    branches: [main, store-prefs-to-flash]
  pull_request:
  workflow_dispatch:

env:
  RUSTUP_TOOLCHAIN: stable

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - run: make test
